version: '3.8'
services:
  api:
    build: .
    container_name: toolbox_backend
    ports:
      - '4000:4000'
  client:
    build: ./client
    container_name: toolbox_frontend
    ports:
      - '3000:3000'
